### ISSUE TITLE
GA - Publicidad - Variacion Interanual Feb'19

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#102]
Reporte “Publicidad – Variación Interanual”: corregir los títulos, el cambio de año debe haber hecho que se desconfigure.

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/3aa2b391-eb4f-4af4-877d-77e33400c71a)

asi se tendria q ver

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/4c7d5b7f-be2b-4fd0-86aa-c2aa5a2e03ae)

**Comment by npzabala** [comment]
Corregido, la variable "Año Ingresado" contenia en su formula un "Si" sin un else.![Plataforma de lanzamiento de BI - Google Chrome.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/b009630b-61e6-4b0f-b5fb-59aa27d3fe34)
