### ISSUE TITLE
GA - Reporte Bienes de Uso

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#108]
Esperando especificaciones del reporte de Bienes de Uso

**Comment by PabloGottig** [comment]
Se inició el análisis de la consulta enviada, se deberá pensar en una solución como fact fotografica que se recargue por período. Tener en cuenta la creación de tablas temporales ya que el volumen va a ser un inconveniente, también será necsario considerar como recargar las fotos historicas considerando el reproceso de los indicadores acumulados. 

Se deja en el server de SQL Test de Corpo una carpeta con las consultas ejecutadas:![image.png](https://images.zenhubusercontent.com/5beef8c5308256459932e5c1/40c02d6a-5a87-4161-aa45-b3e256f72e8f)

Adicionalmente se enviaron algunas consultas al proveedor.

**Comment by PabloGottig** [comment]
Necesitamos que nos repliquen la base productiva para poder avanzar con el análisis.

**Comment by PabloGottig** [comment]
RVMBIE – Maestro de  Bienes
                RVRMVI – Detalle de Bienes
                STMPDH – Maestro de productos
                STRMVI – Movimientos de Stock

**Comment by PabloGottig** [comment]
Chicos respecto al indicador Amortizacion Actualizada (que da todo nulos) lo que tienen que hacer es sumar la acumulada al valor que traiga ese campo, una vez que carguen la IG lo hacen con un UPDATE.

Con esto estarían terminadas las validaciones y para BER dá todo ok contra los datos que mandó Nati.

Cualquier duda me avisan.

Slds! 

De: pgottig@inteligenciaanalitica.com <pgottig@inteligenciaanalitica.com> 
Enviado el: jueves, 25 de abril de 2019 16:57
Para: 'Lucas Ruiz' <lruiz@inteligenciaanalitica.com>; Nicolas Zabala <nzabala@inteligenciaanalitica.com>
Asunto: RV: Migrar a BI reporte de citrix con información de INVERSIONES

Lucas, Nico, les deje dentro de la carpeta del server de Test de DW Corpo el script con el exctractor. 
 

Ya alinee los campos con los de Inversiones Detalle para que la Fact sea bastante parecida, hay un solo campo que no me está trayendo datos que hay que revisarlo, pero no lo que les deje ya pueden empezar a armar el proceso:
1.	Incorporar la extracción al paquete dw_procesos_cwa:
a.	Debe ejecutarse el extractor una vez por cada banco, procesando el período actual y el período anterior (ojo con esto, el script trabaja de a 1 banco y a 1 período por vez)
b.	Los resultados deben cargarse en una IG nueva, que sería el detalle de Amortizaciones
2.	Crear un paquete nuevo, tomando como base el de fact_inversiones_detalle, crear tablas, y relaciones idem la fact inversiones detalle:
a.	Cuenta contable+
b.	Proveedor
c.	Producto
d.	Sucursal
e.	Tiempo (periodo)
f.	Tiempo (fecha de alta)
g.	Cualquier otra relación que sirva dentro del modelo
3.	Modelar la fact en el universo, simil detalle de inversiones, relacionarla con las dims existentes, modelar los contextos.

Lo vamos revisando, cualquier duda me avisan.

Saludos,
Pablo

**Comment by lruiz1** [comment]
Se deberá parametrizar el paquete de carga en la interfaz: Procesos_programar_CWA

**Comment by PabloGottig** [comment]
Mejorar el proceso para que utilice un bucle for each
