### ISSUE TITLE
CA - Verificar Fecha Recibo en Caudales

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#114]
Se debera realizar validaciones del formato de fecha con Abi, ya que hay fechas del periodo actual que tienen fechas muy anteriores.

**Comment by npzabala** [comment]
Se detectan 6 registros donde la fecha de recibo es muy anterior a la fecha de carga.
![cau2.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/e1eb72f0-54a3-4a1d-865d-de0896c31718)

![cau.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/82658e65-c003-4831-b457-4b75645d2974)
