### ISSUE TITLE
CA - Escenarios MIA

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#64]

**Comment by PabloGottig** [comment]
Lucas, de este requerimiento queda algo más para hacer?

**Comment by lruiz1** [comment]
Buen dia Pablo, 

 

Si, me pidió unas nuevas modificaciones para el 2017.

 

Saludos

 

Lucas Ruiz | Consultor BI

Inteligencia Analítica - www.inteligenciaanalitica.com <http://www.inteligenciaanalitica.com> 

Cel. +549 3401 418647 - lruiz@inteligenciaanalitica.com <mailto:lruiz@inteligenciaanalitica.com> 

 

De: PabloGottig [mailto:notifications@github.com] 
Enviado el: jueves, 14 de marzo de 2019 16:29
Para: brosenburt/BER-Corp-RRMM <BER-Corp-RRMM@noreply.github.com>
CC: lruiz1 <lruiz@inteligenciaanalitica.com>; Assign <assign@noreply.github.com>
Asunto: Re: [brosenburt/BER-Corp-RRMM] CA - Escenarios MIA (#64)

 

Lucas, de este requerimiento queda algo más para hacer?

**Comment by lruiz1** [comment]
Agrego procesamiento de escenario mail: vi. 29/03/2019 13:07

**Comment by lruiz1** [comment]
Modificaciones en el retroactivo de Marzo. Corrección de paquetes.
