### ISSUE TITLE
GA - Nuevo G01 con Gastos Corpo

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#68]
Chicos, este reporte:

 

Pónganlo en esta carpeta:

 

Que los Gastos Corpo en una línea, se muestren en el cuadro general, Ej: como el rubo Otros

 

No me da el Presupuesto, debería coincidir con el GA 8, tanto registrado como presupuesto de la 5ta empresa.

 

No entiendo que este Neteado. Y el presupuesto no da.

**Comment by npzabala** [comment]
Chicos: 
1)	Las líneas al pie del cuadro, no coinciden con el GA 8

![1.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/3e6904c2-65ec-46ad-8d28-b4e7bb982595)

 

2)	El P2018 de EXS no me coincide con el del TDG de 2018-12 (Versión que tenía guardada en mis archivos):

![2.png](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/5351ea52-0957-47fb-af50-6657a77e6567)

![3.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/c24b700c-fae8-411c-8152-66ef5825b28a)
