### ISSUE TITLE
GA - Modificaciones GA8 Feb'19

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#72]
Chicos: el presupuesto de inversiones del GA 8 del GBSJ no trae bien la info.
No trae la cuenta “Mejoras sobre Inmuebles” de BSF.  Y por lo tanto se modifica el total de Inversiones.

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/b517c3ff-c0ca-49a7-a8d2-c8ddb8680e95)

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/be8dabe6-6485-49ac-9518-d1102c6fc3ee)

**Comment by npzabala** [comment]
Chicos:
               En el GA 8 hay que modificar lo siguiente:

1)	Corregir el Total de Inversiones – Presupuesto, que no da.
2)	Que el orden de las cuentas de Inversiones, tanto Registrado como Presupuesto, tengan el orden que se observa al pie. BSJ hay que modificarlo seguro.

![1.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/8a59f074-f47e-4a19-8d04-9e3ac29339c0)

3)	En la solapa de BSC no aparecen los valores mensuales:

![2.jpg](https://images.zenhubusercontent.com/5c5c2dac6b37576f0450bb00/2e1b3788-ad49-41f1-9a88-eebdc7af64f4)
