### ISSUE TITLE
GA - Informe de Gastos por Proveedor Feb'19

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#77]
Lucas
Buenos días
Revisando hoy el reporte encontramos una diferencia en Informe de Gastos por Proveedor – Otros Honorarios, en el BI tenemos $5.937.693 y en el Reporte 7.079.777 me parece el error estaría en Proveedor Contabilidad 1.142.084

Me avisas cualquier consulta
Desde ya muchas gracias

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/4d234dd3-f6cc-433c-8f95-d40d0d602ad8)

**Comment by npzabala** [comment]
Se retira por filtro la razón social indicada.
