### ISSUE TITLE
GA - G1-Inversiones 

### ISSUE THREAD

**Issue by lruiz1** [brosenburt/BER-Corp-RRMM#79]
Chicos: para agregarlos último a la lista de prioridades:
 
Por favor corregir en reporte G-01, solapa Inversiones: las cuentas de amortizacion acumulada indicadas en verde debe ubicarse en el otro cuadro.

![image.png](https://images.zenhubusercontent.com/5bf5acdfb8ceee790ed2c791/23d6d1c3-4cda-44a2-a91b-84c96fc5aedf)

**Comment by npzabala** [comment]
Se crean nuevas variables para las secciones TestV / TestV2 y se reubican las cuentas.
